### ISSUE TITLE
bug in classification prediction

### ISSUE THREAD

**Issue by tkuTM** [coreylynch/pyFM#4]
It seems there is a bug in the pyfm_fast.pyx within the prediction part for classification tasks:
 
In the `_predict` method, the outcome is basically calculated in line 252 using the `predict_instance` method. `predict_instance` is evaluating the FM model and then scales the result with the sigmoid function for classification in `_scale_prediction` (line 179), which is fine and which is also needed also for the training part. 
The problem I see, is that this sigmoid transformation is done again in line 252, which basically means, that `_predict` always returns `values > 0.5` because we apply the sigmoid twice. 
There is no effect for the regression taks, due to the difference handling for classification/regression within  `_scale_prediction`.

What do you think?

**Comment by coreylynch** [comment]
Thanks for the find and sorry for the late fix!

**Comment by geekan** [comment]
@coreylynch please check https://github.com/coreylynch/pyFM/pull/6 :)
