### ISSUE TITLE
Not converge when training?

### ISSUE THREAD

**Issue by geekan** [coreylynch/pyFM#7]
You can see the rmse change as below, using the example from README.
Why does it not converge, and how could I fix it?

```
--- git/pyFM ‹master* ?› » python example.py 
Creating validation dataset of 0.01 of training for adaptive regularization
-- Epoch 1
Training RMSE: 0.49676
-- Epoch 2
Training RMSE: 0.44940
-- Epoch 3
Training RMSE: 0.44133
-- Epoch 4
Training RMSE: 0.43757
-- Epoch 5
Training RMSE: 0.43599
-- Epoch 6
Training RMSE: 0.43494
-- Epoch 7
Training RMSE: 0.43381
-- Epoch 8
Training RMSE: 0.43375
-- Epoch 9
Training RMSE: 0.43324
-- Epoch 10
Training RMSE: 0.43272
-- Epoch 11
Training RMSE: 0.43310
-- Epoch 12
Training RMSE: 0.43255
-- Epoch 13
Training RMSE: 0.43229
-- Epoch 14
Training RMSE: 0.43235
-- Epoch 15
Training RMSE: 0.43214
-- Epoch 16
Training RMSE: 0.43237
-- Epoch 17
Training RMSE: 0.43242
-- Epoch 18
Training RMSE: 0.43247
-- Epoch 19
Training RMSE: 0.43308
-- Epoch 20
Training RMSE: 0.44136
-- Epoch 21
Training RMSE: 0.44681
-- Epoch 22
Training RMSE: 0.44714
-- Epoch 23
Training RMSE: nan
```

**Comment by coreylynch** [comment]
This should be fixed now. Thanks.

**Comment by geekan** [comment]
@coreylynch Thanks for your work! But I test it for 300 iters and it cannot converge too, shouldn't I set a big iteration limit?

**Comment by coreylynch** [comment]
Hey @geekan I believe the learning rate is just too high in the example (I didn't do any tuning or grid search to find the most appropriate one). If you take a look at this: https://gist.github.com/coreylynch/7a33ba902b2e14315388, decreasing the learning rate to 0.001 allows the model to train for 600 iterations without diverging. Thanks!
